### ISSUE TITLE
Missing Stream module in referenced in aiko_services/main/__init__.py

### ISSUE THREAD

**Issue by pdmct** [geekscape/aiko_services#12] opened 2024-06-17 12:18 UTC
ENV:
Ubuntu WSL2
(aiko_services) ➜  aloha_honua git:(master) ✗ uname -a
Linux TYCHO 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Python 3.12.3

PROBLEM:
After cloning and installing aiko_services and running system_start.sh or trying to import `aiko_services` I get the following error:
```
➜  aiko_services git:(master) ✗ python
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiko_services
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/projects/aiko_services/src/aiko_services/__init__.py", line 1, in <module>
    import aiko_services.main
  File "/home/me/projects/aiko_services/src/aiko_services/main/__init__.py", line 56, in <module>
    from .stream import StreamEventDescription, StreamEvent, StreamState
ModuleNotFoundError: No module named 'aiko_services.main.stream'
```

This import is referring to a module `stream` that doesn't appear in the main branch. It looks like there are some old versions of this module on other branches in the repo.

**Comment by geekscape** [comment] 2024-06-18 05:40
Thanks !  A oversight caused by failing to add/commit [src/aiko_services/main/stream.py](https://github.com/geekscape/aiko_services/blob/master/src/aiko_services/main/stream.py)

Fixed by _master_ branch commit [d4ee76a](https://github.com/geekscape/aiko_services/commit/d4ee76ad93d94f4974f876dd4e59c4fc5c64bf8e)

**Closed by geekscape** 2024-06-18 05:40 UTC
